### ISSUE TITLE
Error trying to connect with the ConfigurationManager at the Connector version 5 above

### ISSUE THREAD

**Issue by edgardmarx** [Fraunhofer-IVI/Datenraum-Mobilitaet#3]
Dear all,

I am facing problem trying to connect to make my ConfigurationManager connect to the IDS Connector.
I tried all tag versions above and inclusive version 5.

I have no issue connecting to the version 4.3.1.

The error shown in all versions is:

```

15:14:13.136 [main] WARN - ---- [DataspaceConnectorClient getConfiguration] Could not get ConfigurationModel from https://ids.eccenca.dev:9090/admin/api/configuration with user admin. Response: 404 -
15:14:14.096 [main] ERROR - ---- [DataspaceConnectorClient getConfiguration] SERIALIZER.deserialize threw IOException
15:14:14.096 [main] ERROR - Could not extract class from input message
java.io.IOException: Could not extract class from input message
```

thanks

**Comment by sebplorenz** [comment]
Hi Edgard,
the ConfigurationManager is not yet working with DSC version 5 or above. We have to wait for an official release that supports DSC v5. In fact we have to wait for this branch https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/tree/Dataspace-Connector-v5 to be merged.
Regards, Sebastian

**Comment by sebplorenz** [comment]
The ConfigurationManager has been updated to run with DSC version 6.x. Please see the current docs on https://github.com/International-Data-Spaces-Association/DataspaceConnectorUI for details.

Btw. This repository has been moved to https://github.com/Mobility-Data-Space/mobility-data-space
Please add upcoming questions there.
Regards, Sebastian
