### ISSUE TITLE
The Production MDS Broker metadata is been pointing to the test broker

### ISSUE THREAD

**Issue by edgardmarx** [Fraunhofer-IVI/Datenraum-Mobilitaet#5]
Somehow the metadata from the Production MDS Broker (broker.mobilitydataspace.io) is been pointed to the test broker.

e.g. https://broker.mobilitydataspace.io/connector/connector?id=https%3A%2F%2Fbroker.**test**.mobilitydataspace.io%2Fconnectors%2F-1730255123

**Comment by sebplorenz** [comment]
Will be fixed with the new Broker deployment soon.
